### ISSUE TITLE
[possible TODO clarification, not really an issue] +4 bytes when reading the length from ASN1 encoded certificate

### ISSUE THREAD

**Issue by Muzosh** [web-eid/libpcsc-cpp#17]
https://github.com/web-eid/libpcsc-cpp/blob/0483f24fa328cac4280a0ffab1762734f51d479e/src/utils.cpp#L133-L142

In the source code there is comment about digging up the reason why the +4 is included in the computation. I have found out it is most probably included because of the first 4 bytes the code uses to actually read the length.

![image](https://user-images.githubusercontent.com/30979983/167619184-1adee102-f8d6-4bc6-8dff-cd3cc4e0f17c.png)

In the next step the program usually uses this length to read whole certificate from the card, so the first 4 bytes need to be included, otherwise it would be 4 bytes shorter.

This is not really an issue, but I have been in contact with @mrts who told me to make a comment about it here. Maybe in the future it might confuse people.

**Comment by mrts** [comment]
Thanks! Fixed in 8c6bfdc.
