### ISSUE TITLE
Exception is thrown when SW1/SW2 = 6CXX

### ISSUE THREAD

**Issue by gunnarhelgason** [web-eid/libpcsc-cpp#20]
Currently, when the status word from the card is 6CXX, an exception is thrown:
https://github.com/web-eid/libpcsc-cpp/blob/8c6bfdceaeb8415f6a772972ff63912d73ce61b5/src/SmartCard.cpp#L218-L220

When receiving 6CXX, one is supposed to resend the command APDU with Le=XX. However, since an exception is thrown, the ResponseApdu object is not returned to the caller, and as a result the SW2 value cannot be accessed to determine the correct Le.

I think this can be solved by simply removing the code that throws the exception, and let the caller handle it.

What do you think?

**Comment by mrts** [comment]
Thank you for the suggestion! I'll discuss the tradeoffs within the team and will get back to you.
(See [this](https://github.com/open-eid/qt-common/blob/77a979e511033df92171de3ff7b5315b25248746/QPCSC.cpp#L409-L414) for a possible solution.)

**Comment by mrts** [comment]
We will implement this eventually, however this is not currently a high priority for us. Feel free to raise this again if it is important for you and you want us to prioritize this more.

**Comment by kristelmerilain** [comment]
Thank you for the feedback.
I will close this issue since the libpcsc-cpp code was moved to libelectronic-id repository.
We are happy to accept your proposals in the libelectronic-id repository: https://github.com/web-eid/libelectronic-id.
