### ISSUE TITLE
Add reference to Reader to SmartCard and delegate SmartCard::atr() to reader.atr

### ISSUE THREAD

**Issue by mrts** [web-eid/libpcsc-cpp#9]
I originally envisioned that `libpcsc-cpp` could be used in embedded environments where every byte counts and so didn't want to have a copy of the ATR both in `Reader` and `SmartCard`, so I used `std::move` to move it from `Reader`. Now I think this was an inadequate premature optimization, and `SmartCard` takes all data that it uses by copy.

I took a second look and I actually think the best way to have only a single copy of the ATR is to add a reference to `Reader` to `SmartCard` so that `SmartCard::atr()` just does `return reader.atr`. The trick, though, is to assure that the `Reader` object remains alive, it was originally meant to live on the stack and possibly have shorter lifetime than `SmartCard`.

_Originally posted by @mrts in https://github.com/web-eid/libpcsc-cpp/pull/8#issuecomment-847913167_

**Comment by kristelmerilain** [comment]
Thank you for the feedback.
I will close this issue since the libpcsc-cpp code was moved to libelectronic-id repository.
We are happy to accept your proposals in the libelectronic-id repository: https://github.com/web-eid/libelectronic-id.
